### ISSUE TITLE
Update to the latest versions

### ISSUE THREAD

**Issue by collinglass** [mhamrah/ansible-mesos-playbook#13]
Hi, this is very useful but getting to be over a year outdated. It would be nice if you updated the versions of mesos, marathon, docker, etc.

**Comment by jaytaylor** [comment]
I'm sure a PR would be welcome :)

**Comment by mhamrah** [comment]
Unfortunately I'm not really working with this project anymore. I'd gladly accept a pull request, but if you are looking for an alternative, check the forks or try https://github.com/CiscoCloud/microservices-infrastructure.
