### ISSUE TITLE
Cannot run librarian-ansible install.

### ISSUE THREAD

**Issue by sonali2197** [mhamrah/ansible-mesos-playbook#9]
Hi,

I installed ansible and librarian-ansible. I'm trying to run 'librarian-ansible install' but it keeps failing with the following error. Am i missing something here? the syntax of the Ansiblefile should be correct (i'm using the one from this playbook). Any help would be appreciated!

[root@svdpdac015 ansible-mesos-playbook]# librarian-ansible install
/root/ansible-mesos-playbook/Ansiblefile:7:in `run': compile error (SyntaxError)
/root/ansible-mesos-playbook/Ansiblefile:7: syntax error, unexpected ':', expecting $end
  github: "mhamrah/ansible-docker"
         ^
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/dsl.rb:79:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/dsl.rb:73:in `tap'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/dsl.rb:73:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/dsl.rb:17:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/environment.rb:148:in `dsl'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/specfile.rb:15:in `read'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:17:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-ansible-1.0.6/lib/librarian/ansible/cli.rb:41:in `install'
        from /usr/lib64/ruby/gems/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `__send__'
        from /usr/lib64/ruby/gems/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/1.8/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/1.8/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
        from /usr/lib64/ruby/gems/1.8/gems/librarian-ansible-1.0.6/bin/librarian-ansible:7
        from /usr/bin/librarian-ansible:23:in `load'
        from /usr/bin/librarian-ansible:23
[root@svdpdac015 ansible-mesos-playbook]#

Sonali

**Comment by jaytaylor** [comment]
Can you paste us the contents of your `Ansiblefile`?

**Comment by sonali2197** [comment]
Contents of my Ansiblefile:

#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "ansible-docker",
  github: "mhamrah/ansible-docker"
role "ansible-java8",
  github: "mhamrah/ansible-java8"
role "ansible-zookeeper",
  github: "mhamrah/ansible-zookeeper"
role "ansible-marathon",
  github: "mhamrah/ansible-marathon"
role "ansible-mesos",
  github: "mhamrah/ansible-mesos"
role "ansible-consul",
  github: "mhamrah/ansible-consul"

I'm using version 1.9 for ansible and 1.0.6 for librarian-ansible

Thanks!
S

**Comment by mhamrah** [comment]
I'm on 1.0.6 too, but my anise is 1.8.2. Not sure if that's a difference;
i'll try upgrading tonight to attempt to repro.

**Comment by sonali2197** [comment]
Any luck?

**Comment by mhamrah** [comment]
Sorry, I just had an opportunity to look at this. I unfortunately can't reproduce. Here are some suggestions:

- Try cloning the repo again into a fresh directory, and run librarian-ansible install
- Check folder permissions, maybe something is interfering with writing files?
- Not sure if there's a verbose/debug mode for librarian-ansible, but try that to see if you can get a better message.
- It's possible your editor is effecting whitespace/syntax, which is somehow throwing off the Ansiblefile (this is a weak theory)

You actually don't the librarian-ansible if you want to run the playbook, it's just used for dependency management.  You just need to clone the repos listed in that file and make sure Ansible knows how to find them, i.e. by cloning them all into a roles/ folder.

**Comment by sonali2197** [comment]
Hi,

So this might be a stupid question (I've never used chef or ansible before)

I created a roles folder and cloned all the repos (docker, mesos, marathon, java8, zookeeper and consul).

Each of these have a .yml file. How do I install these roles? What command would I use?

**Comment by mhamrah** [comment]
This is more in the world of how-to-use ansible, and the ansible website provides a lot of great documentation. Here's a quick start video that I found helpful: http://docs.ansible.com/quickstart.html

To quickly answer your question you shouldn't need to worry about anything in those folders. In the playbook.yml file the roles for mesos are declared, and ansible knows how to find those definitions based on the folder structure in the roles/ directory.

**Comment by sonali2197** [comment]
Thanks! That was helpful!

However, it fails when trying to install HAProxy citing “ No Package matching haproxy found available, installed or updated”. Do you know if it requires some additional roles not specified in Ansiblefile?

**Comment by mhamrah** [comment]
That's probably because haproxy isn't available in your repo. I believe you left a comment in ansible-zookeeper saying you're on RHEL. HAProxy should be available via EPEL, but my guess is you're using a proxy or it's called something different. Check with your sysadmins or enable EPEL explicitly. Not sure how on RHEL.

**Comment by sonali2197** [comment]
I fixed the haproxy issue. I had to update the red hat subscription channel to include the redhat package for haproxy on my servers. Thanks!

Now I have a zookeeper issue where the playbook won’t recognize the service.
